In [ ]:
import tensorflow as tf

In [ ]:
# Zero Dimensional tensor

tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
# One Dimensional tensor

tensor_one_d = tf.constant([2,0,-3], dtype=tf.float32)
casted_tensor_one_d = tf.cast(tensor_one_d, dtype=tf.int32)

print(tensor_one_d)
print(casted_tensor_one_d)

tf.Tensor([ 2.  0. -3.], shape=(3,), dtype=float32)
tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)


In [ ]:
# One Dimensional tensor

tensor_one1_d = tf.constant([2,0,-3,8,90.5])
print(tensor_one1_d)

tf.Tensor([ 2.   0.  -3.   8.  90.5], shape=(5,), dtype=float32)


In [ ]:
# Two Dimensional tensor

tensor_two_d = tf.constant([
                            [1,2,0],
                            [3,5,-1],
                            [1,5,6],
                            [2,3,8]
                          ])
print(tensor_two_d)

print(tensor_two_d[0:3,0:2])

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)
tf.Tensor(
[[1 2]
 [3 5]
 [1 5]], shape=(3, 2), dtype=int32)


In [ ]:
# Three Dimensional tensor

tensor_three_d = tf.constant(
    [
        [
           [1,2,0],
           [3,5,-1]
        ],
        [
            [10,2,0],
            [1,0,2]
        ],
        [
            [5,8,0],
            [2,7,0]
        ],
        [
            [2,1,9],
            [4,-3,32]
        ]
    ]
)

print(tensor_three_d)
print(tensor_three_d[2:3, 0:, :2])

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)
tf.Tensor(
[[[5 8]
  [2 7]]], shape=(1, 2, 2), dtype=int32)


In [ ]:
# Four Dimensional tensor

tensor_four_d = tf.constant([
    [
        [
           [1,2,0],
           [3,5,-1]
        ],
        [
            [10,2,0],
            [1,0,2]
        ],
        [
            [5,8,0],
            [2,7,0]
        ],
        [
            [2,1,9],
            [4,-3,32]
        ]
    ],
    [
        [
           [16,21,0],
           [3,52,-15]
        ],
        [
            [10,52,60],
            [21,40,32]
        ],
        [
            [53,8,0],
            [2,77,0]
        ],
        [
            [2,31,9],
            [4,-36,352]
        ]
    ],
    [
        [
           [69,62,0],
           [34,5,-1]
        ],
        [
            [10,2,40],
            [1,20,2]
        ],
        [
            [35,8,0],
            [25,7,30]
        ],
        [
            [2,15,9],
            [4,-23,432]
        ]
    ],
])

print(tensor_four_d)

tf.Tensor(
[[[[  1   2   0]
   [  3   5  -1]]

  [[ 10   2   0]
   [  1   0   2]]

  [[  5   8   0]
   [  2   7   0]]

  [[  2   1   9]
   [  4  -3  32]]]


 [[[ 16  21   0]
   [  3  52 -15]]

  [[ 10  52  60]
   [ 21  40  32]]

  [[ 53   8   0]
   [  2  77   0]]

  [[  2  31   9]
   [  4 -36 352]]]


 [[[ 69  62   0]
   [ 34   5  -1]]

  [[ 10   2  40]
   [  1  20   2]]

  [[ 35   8   0]
   [ 25   7  30]]

  [[  2  15   9]
   [  4 -23 432]]]], shape=(3, 4, 2, 3), dtype=int32)


In [ ]:
# Return the shape

print(tensor_zero_d.shape)
print(tensor_one_d.shape)
print(tensor_one1_d.shape)
print(tensor_two_d.shape)
print(tensor_three_d.shape)
print(tensor_four_d.shape)

()
(3,)
(5,)
(4, 3)
(4, 2, 3)
(3, 4, 2, 3)


In [ ]:
# Return the dimension

print(tensor_zero_d.ndim)
print(tensor_one_d.ndim)
print(tensor_one1_d.ndim)
print(tensor_two_d.ndim)
print(tensor_three_d.ndim)
print(tensor_four_d.ndim)

0
1
1
2
3
4


In [ ]:
# Boolean Tensors

tensor_bool = tf.constant([True,True,False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [ ]:
# String Tensors

tensor_string = tf.constant(["Hello World", "Hi"])
print(tensor_string)

tf.Tensor([b'Hello World' b'Hi'], shape=(2,), dtype=string)


In [ ]:
import numpy as np

In [ ]:
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [ ]:
# Converting a Numpy Array to Tensor

converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


In [ ]:
# Eye Tensor ( Construct an identity matrix, or a batch of matrices. )

eye_tensor1 = tf.eye(
    num_rows = 3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)

eye_tensor2 = tf.eye(
    num_rows = 3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.bool,
    name=None
)

eye_tensor3 = tf.eye(
    num_rows = 10,
    num_columns=5,
    batch_shape=None,
    dtype=tf.dtypes.int64,
    name=None
)

eye_tensor4 = tf.eye(
    num_rows = 5,
    num_columns=None,
    batch_shape=[3,],
    dtype=tf.dtypes.int64,
    name=None
)

print(eye_tensor1)
print(3*eye_tensor1)

print(eye_tensor2)

print(eye_tensor3)
print(3*eye_tensor3)

print(eye_tensor4)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ True False False]
 [False  True False]
 [False False  True]], shape=(3, 3), dtype=bool)
tf.Tensor(
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]], shape=(10, 5), dtype=int64)
tf.Tensor(
[[3 0 0 0 0]
 [0 3 0 0 0]
 [0 0 3 0 0]
 [0 0 0 3 0]
 [0 0 0 0 3]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]], shape=(10, 5), dtype=int64)
tf.Tensor(
[[[1 0 0 0 0]
  [0 1 0 0 0]
  [0 0 1 0 0]
  [0 0 0 1 0]
  [0 0 0 0 1]]

 [[1 0 0 0 0]
  [0 1 0 0 0]
  [0 0 1 0 0]
  [0 0 0 1 0]
  [0 0 0 0 1]]

 [[1 0 0 0 0]
  [0 1 0 0 0]
  [0 0 1 0 0]
  [0 0 0 1 0]
  [0 0 0 0 1]]], shape=(3, 5, 5), dtype=int64)


In [ ]:
# Fill Method ( Creates a tensor filled with a scalar value. )

fill_tensor1 = tf.fill(
    [3,4], 5, name=None, layout=None
)

fill_tensor2 = tf.fill(
    [3,4], 5, name=None, layout=None
)

print(fill_tensor1)
print(fill_tensor2)

tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)


In [ ]:
# Ones Method ( Creates a tensor with all elements set to one (1). )

ones_tensor = tf.ones(
    [3,5,3,2],
    dtype=tf.dtypes.float32,
    name=None,
    layout=None
)
print(ones_tensor)

tf.Tensor(
[[[[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]]


 [[[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]]


 [[[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]]], shape=(3, 5, 3, 2), dtype=float32)


In [ ]:
# Ones Like Method ( Creates a tensor of all ones that has the same shape as the input. )

tf.ones_like(
    fill_tensor2, dtype=None, name=None, layout=None
)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)>

In [ ]:
# Zeros Method ( Creates a tensor with all elements set to zero. )

zeros_tensor = tf.zeros(
    [3,5],
    dtype=tf.dtypes.float32,
    name=None,
    layout=None
)
print(zeros_tensor)

tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], shape=(3, 5), dtype=float32)


In [ ]:
# Shape Method ( Returns a tensor containing the shape of the input tensor. )

shape_tensor = tf.shape(
    fill_tensor1, out_type=None, name=None
)
print(shape_tensor)

tf.Tensor([3 4], shape=(2,), dtype=int32)


In [ ]:
# Rank Method ( Returns the rank of a tensor. )

t = tf.constant([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]])
tf.rank(t)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
# Size Method ( Returns the size of a tensor. )

# tf.size(
#     input, out_type=None, name=None
# )

# Returns a 0-D Tensor representing the number of elements in input of type out_type. Defaults to tf.int32.

t = tf.constant([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]])
tf.size(t)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [ ]:
# Random Normal Method ( Outputs random values from a normal distribution. )

random_normal_tensor1 = tf.random.normal(
    [3,5],
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

random_normal_tensor2 = tf.random.normal(
    [3,2],
    mean=100.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

print(random_normal_tensor1)
print(random_normal_tensor2)

tf.Tensor(
[[-1.2442502  -1.1443207  -0.80716383  1.2356743  -0.2788294 ]
 [-0.12809137 -0.51027876 -1.2717333   0.4982445   1.6752826 ]
 [-0.28305998 -0.52798027 -0.09556457  1.0849276  -2.2254894 ]], shape=(3, 5), dtype=float32)
tf.Tensor(
[[99.42869  99.287155]
 [99.351204 98.81927 ]
 [98.60877  99.73159 ]], shape=(3, 2), dtype=float32)


In [ ]:
# Random Normal Method ( Outputs random values from a uniform distribution. )

random_uniform_tensor1 = tf.random.uniform(
    [3,5],
    minval=0,
    maxval=None,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

random_uniform_tensor2 = tf.random.uniform(
    [5],
    minval=100,
    maxval=500,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

print(random_uniform_tensor1)
print(random_uniform_tensor2)

tf.Tensor(
[[0.11435914 0.8329456  0.89484286 0.9148203  0.5795454 ]
 [0.25399446 0.84935606 0.6324642  0.14592671 0.4627794 ]
 [0.6538658  0.8955959  0.04225504 0.9115442  0.64700913]], shape=(3, 5), dtype=float32)
tf.Tensor([455.62598 460.62155 399.12256 484.32288 361.1847 ], shape=(5,), dtype=float32)


In [ ]:
# To set a constant global tensor with seed

tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,], maxval=3, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=3, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=3, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=3, dtype=tf.int32, seed=10))

tf.Tensor([2 0 1], shape=(3,), dtype=int32)
tf.Tensor([1 0 0], shape=(3,), dtype=int32)
tf.Tensor([0 1 1], shape=(3,), dtype=int32)
tf.Tensor([2 1 2], shape=(3,), dtype=int32)


In [ ]:
# To set a constant global tensor with seed


tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,], maxval=3, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=3, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=3, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=3, dtype=tf.int32, seed=10))

tf.Tensor([2 0 1], shape=(3,), dtype=int32)
tf.Tensor([1 0 0], shape=(3,), dtype=int32)
tf.Tensor([0 1 1], shape=(3,), dtype=int32)
tf.Tensor([2 1 2], shape=(3,), dtype=int32)


In [ ]:
# Tensor Indexing

tensor_indexed = tf.constant([3,6,2,4,6,66,7])
print(tensor_indexed)
print(tensor_indexed[0:4])
print(tensor_indexed[1:6:4])
print(tensor_indexed[3:])
print(tensor_indexed[:4])

tf.Tensor([ 3  6  2  4  6 66  7], shape=(7,), dtype=int32)
tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)
tf.Tensor([ 6 66], shape=(2,), dtype=int32)
tf.Tensor([ 4  6 66  7], shape=(4,), dtype=int32)
tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)


In [ ]:
print(tf.range(2,5))
print(tf.range(2,5+1))

tf.Tensor([2 3 4], shape=(3,), dtype=int32)
tf.Tensor([2 3 4 5], shape=(4,), dtype=int32)


In [ ]:
# Absolute Value

x_abs = tf.constant([-2.34, 3.45])
tf.abs(x_abs)

x_abs_complex = tf.constant([-2.25 + 4.75j])
tf.abs(x_abs_complex)

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([5.25594901])>

In [ ]:
tf.sqrt((-2.25)**2 + 4.75**2)

<tf.Tensor: shape=(), dtype=float32, numpy=5.255949>

In [ ]:
# Operations

x1 = tf.constant([5,3,6,6,4,6], dtype = tf.int32)
x2 = tf.constant([7], dtype = tf.int32)

print(tf.add(x1,x2))
print(tf.multiply(x1,x2))
print(tf.subtract(x1,x2))
print(tf.divide(x1,x2))
print(tf.math.divide_no_nan(x1,x2))

tf.Tensor([12 10 13 13 11 13], shape=(6,), dtype=int32)
tf.Tensor([35 21 42 42 28 42], shape=(6,), dtype=int32)
tf.Tensor([-2 -4 -1 -1 -3 -1], shape=(6,), dtype=int32)
tf.Tensor([0.71428571 0.42857143 0.85714286 0.85714286 0.57142857 0.85714286], shape=(6,), dtype=float64)
tf.Tensor([0.71428571 0.42857143 0.85714286 0.85714286 0.57142857 0.85714286], shape=(6,), dtype=float64)


In [ ]:
tf.pow(tf.constant(2), tf.constant(3))

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [ ]:
tf.transpose(tensor_two_d)

contmat = tf.constant([1,2,0])
tf.transpose(contmat)

print(contmat.shape)
print(tf.transpose(contmat).shape)


(3,)
(3,)


In [ ]:
import tensorflow as tf

# Example 1-dimensional tensors (vectors)
x1 = tf.constant([1, 2, 3], dtype=tf.float32)
x2 = tf.constant([4, 5, 6], dtype=tf.float32)

# Reshape the vectors into 2-dimensional tensors (matrices)
x1_reshaped = tf.reshape(x1, (1, -1))  # Shape (1, 3)
x2_reshaped = tf.reshape(x2, (1, -1))  # Shape (1, 3)

# Transpose the second matrix to match dimensions for matmul
x2_reshaped_T = tf.transpose(x2_reshaped)  # Shape (3, 1)

# Perform matrix multiplication
result = tf.linalg.matmul(x1_reshaped, x2_reshaped_T)

print(result)


tf.Tensor([[32.]], shape=(1, 1), dtype=float32)


In [ ]:
import tensorflow as tf

# Example 1-dimensional tensor (vector)
x1 = tf.constant([1, 2, 3], dtype=tf.float32)

# Reshape the vector into a 2-dimensional tensor (matrix)
x1_reshaped = tf.reshape(x1, (1, -1))  # Shape (1, 3) or (-1, 1) for (3, 1)

# Perform SVD
s, u, v = tf.linalg.svd(x1_reshaped)

print("Singular values:", s)
print("Left singular vectors (U):", u)
print("Right singular vectors (V):", v)


Singular values: tf.Tensor([3.7416573], shape=(1,), dtype=float32)
Left singular vectors (U): tf.Tensor([[-1.]], shape=(1, 1), dtype=float32)
Right singular vectors (V): tf.Tensor(
[[-0.26726127]
 [-0.53452253]
 [-0.8017838 ]], shape=(3, 1), dtype=float32)


In [ ]:
# Summing elements in column and row

A = np.array([[2,6,5,2],
             [2,-2,2,3],
             [1,5,4,0]])

print(np.einsum('ij -> i', A))
print(np.einsum('ij -> j', A))

[15  5 10]
[ 5  9 11  5]


In [ ]:
import numpy as np


B = np.random.randn(2,4,4,2) #bcij
C = np.random.randn(2,4,4,1) #bcik

np.einsum("bcik,bcij -> bckj", C,B).shape

(2, 4, 1, 2)

In [ ]:
# Expand Size

import tensorflow as tf

x = tf.constant([[[2,3,4,5]]])
print(x.shape)
print(tf.expand_dims(x, axis=0))

(1, 1, 4)
tf.Tensor([[[[2 3 4 5]]]], shape=(1, 1, 1, 4), dtype=int32)


In [ ]:
import tensorflow as tf
x = tf.constant([[[2,3,4,5]]])

for i in range(2):
  x_squeezed = tf.squeeze(x, axis = 0)

print(x_squeezed)

tf.Tensor([[2 3 4 5]], shape=(1, 4), dtype=int32)


In [ ]:
# Concatination

t1 = [[1,2,3],
      [4,5,6]]

t2 = [[7,8,9],
      [10,11,12]]

print(tf.constant(t1).shape)
print(tf.constant(t2).shape)

print(tf.concat([t1,t2], axis = 0))  # will combine like rows (one below other)
print(tf.concat([t1,t2], axis = 1))  # will combine like columns (next to each other)

(2, 3)
(2, 3)
tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]], shape=(4, 3), dtype=int32)
tf.Tensor(
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]], shape=(2, 6), dtype=int32)


In [ ]:
# Stack

print(tf.stack([t1,t2], axis = 0))
print(tf.stack([t1,t2], axis = 1))
print(tf.stack([t1,t2], axis = 2))

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)
tf.Tensor(
[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)
tf.Tensor(
[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]], shape=(2, 3, 2), dtype=int32)


In [ ]:
t = tf.constant([[1, 2, 3], [4, 5, 6]])
paddings = tf.constant([[1, 1,], [2, 2]])
# 'constant_values' is 0.
# rank of 't' is 2.
print(tf.pad(t, paddings, "CONSTANT"))   # [[0, 0, 0, 0, 0, 0, 0],
                                         #  [0, 0, 1, 2, 3, 0, 0],
                                         #  [0, 0, 4, 5, 6, 0, 0],
                                         #  [0, 0, 0, 0, 0, 0, 0]]

print(tf.pad(t, paddings, "REFLECT"))    # [[6, 5, 4, 5, 6, 5, 4],
                                         #  [3, 2, 1, 2, 3, 2, 1],
                                         #  [6, 5, 4, 5, 6, 5, 4],
                                         #  [3, 2, 1, 2, 3, 2, 1]]

print(tf.pad(t, paddings, "SYMMETRIC"))  # [[2, 1, 1, 2, 3, 3, 2],
                                         #  [2, 1, 1, 2, 3, 3, 2],
                                         #  [5, 4, 4, 5, 6, 6, 5],
                                         #  [5, 4, 4, 5, 6, 6, 5]]

tf.Tensor(
[[0 0 0 0 0 0 0]
 [0 0 1 2 3 0 0]
 [0 0 4 5 6 0 0]
 [0 0 0 0 0 0 0]], shape=(4, 7), dtype=int32)
tf.Tensor(
[[6 5 4 5 6 5 4]
 [3 2 1 2 3 2 1]
 [6 5 4 5 6 5 4]
 [3 2 1 2 3 2 1]], shape=(4, 7), dtype=int32)
tf.Tensor(
[[2 1 1 2 3 3 2]
 [2 1 1 2 3 3 2]
 [5 4 4 5 6 6 5]
 [5 4 4 5 6 6 5]], shape=(4, 7), dtype=int32)


In [ ]:
import numpy as np

params = tf.constant(['p0', 'p1', 'p2', 'p3', 'p4', 'p5'])
params[3].numpy()

b'p3'

In [ ]:
tf.gather(params, 3).numpy()

b'p3'

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
with tf.device('GPU:0'):
  x_var = tf.Variable(0.2)

print(x_var.device)

/job:localhost/replica:0/task:0/device:CPU:0
